In [1]:
import numpy as np 


In [2]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

## Array Creation¶


In [11]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [14]:
b.dtype

dtype('float64')

In [15]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [20]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [21]:
np.linspace(0, 2, 9) 


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
x = np.linspace(0, 2 * np.pi, 100) 
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [23]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

## Basic Operations

In [24]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [25]:
c = a - b
c

array([20, 29, 38, 47])

In [26]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [27]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [28]:
 a < 35

array([ True,  True, False, False])

In [124]:
A = np.array([[1, 1],
              [0, 1]])

In [128]:
B = np.array([2,0])

In [129]:
A * B     # elementwise product

array([[2, 0],
       [0, 0]])

In [130]:
A @ B     # matrix product

array([2, 0])

In [123]:
np.dot(A,B)    # dot product

array([[2],
       [0]])

In [104]:
a = np.ones((2, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [105]:
b = np.random.random((2, 3))
b

array([[0.22245904, 0.35965653, 0.94581924],
       [0.16206479, 0.24711982, 0.83851116]])

In [108]:
a *= 3
a

array([[9, 9, 9],
       [9, 9, 9]])

In [107]:
b += a
b

array([[3.22245904, 3.35965653, 3.94581924],
       [3.16206479, 3.24711982, 3.83851116]])

In [110]:
a

array([[9, 9, 9],
       [9, 9, 9]])

In [111]:
a.min()

9

In [112]:
a.max()

9

In [113]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
b.sum(axis=0)     # sum of each column

array([12, 15, 18, 21])

In [115]:
b.min(axis=1)     # min of each row

array([0, 4, 8])

In [116]:
 b.cumsum(axis=0)  # cumulative sum along each row

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

## universal Function

In [54]:
B = np.arange(3)
B

array([0, 1, 2])

In [55]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [56]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [57]:
C = np.array([2., -1., 4.])

In [58]:
np.add(B, C)

array([2., 0., 6.])

## Indexing, Slicing and Iterating

In [59]:
a = np.arange(10)**3
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [60]:
a[2]

8

In [61]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [62]:
a[:6:2] = 1000 # from start to position 6, exclusive, set every 2nd element to 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [63]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [65]:
for i in a:
     print(i**(1 / 3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [66]:
b = np.arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
b[2,2]

8

In [68]:
b[0:3, 1]

array([1, 4, 7])

In [69]:
b[:, 1]  

array([ 1,  4,  7, 10])

In [70]:
b[1:3, :]

array([[3, 4, 5],
       [6, 7, 8]])

In [71]:
b[-1] 

array([ 9, 10, 11])

In [72]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [74]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [75]:
a[b] = 0 
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

## shape manipulation 

In [76]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[2., 2., 7., 2.],
       [4., 9., 9., 7.],
       [5., 2., 1., 9.]])

In [77]:
a.shape

(3, 4)

In [78]:
a.ravel()

array([2., 2., 7., 2., 4., 9., 9., 7., 5., 2., 1., 9.])

In [79]:
a.reshape(6, 2)

array([[2., 2.],
       [7., 2.],
       [4., 9.],
       [9., 7.],
       [5., 2.],
       [1., 9.]])

In [80]:
a.T 

array([[2., 4., 5.],
       [2., 9., 2.],
       [7., 9., 1.],
       [2., 7., 9.]])

In [81]:
a.T.shape

(4, 3)

In [82]:
a.shape

(3, 4)

In [83]:
#The reshape function returns its argument with a modified shape, 
#whereas the ndarray.resize method modifies the array itself:
a.resize((2, 6))
a

array([[2., 2., 7., 2., 4., 9.],
       [9., 7., 5., 2., 1., 9.]])

In [84]:
a.reshape(3, -1)

array([[2., 2., 7., 2.],
       [4., 9., 9., 7.],
       [5., 2., 1., 9.]])

# stacking arrays

In [85]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[5., 1.],
       [6., 7.]])

In [86]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[6., 9.],
       [0., 5.]])

In [87]:
np.vstack((a, b))

array([[5., 1.],
       [6., 7.],
       [6., 9.],
       [0., 5.]])

In [88]:
np.hstack((a, b))


array([[5., 1., 6., 9.],
       [6., 7., 0., 5.]])

In [89]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [90]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[4., 0., 6., 8., 5., 2., 8., 5., 5., 7., 1., 8.],
       [6., 7., 1., 8., 1., 0., 8., 8., 8., 4., 2., 0.]])

In [91]:
np.hsplit(a, 3)

[array([[4., 0., 6., 8.],
        [6., 7., 1., 8.]]),
 array([[5., 2., 8., 5.],
        [1., 0., 8., 8.]]),
 array([[5., 7., 1., 8.],
        [8., 4., 2., 0.]])]

In [92]:
np.hsplit(a, (3, 4)) # Split `a` after the third and the fourth column

[array([[4., 0., 6.],
        [6., 7., 1.]]),
 array([[8.],
        [8.]]),
 array([[5., 2., 8., 5., 5., 7., 1., 8.],
        [1., 0., 8., 8., 8., 4., 2., 0.]])]

In [93]:
x = np.arange(0, 10, 2)
x

array([0, 2, 4, 6, 8])

In [94]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [95]:
m = np.vstack([x, y])
m


array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [96]:
xy = np.hstack([x, y])
xy

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])